name: Run test & Upload coverage reports to codecov.io

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run test:coverage
      - name: Save coverage report artifact
        if: ${{ matrix.node-version == (strategy.matrix.node-version[-1]) }} # latest
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage
  upload:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Load coverage report artifact
        uses: actions/download-artifact@v4
        with:
          name: coverage-report
          path: coverage
      - name: Upload coverage reports to codecov.io
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: niceman114/test-codecov
